apiVersion: v2
name: sulfoxide-xenon
description: Metrics Server
type: application
version: 1.5.0
appVersion: "3.11.0"
dependencies:
  - name: metrics-server
    version: 3.11.0
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
