serviceTree:
  landscape: &landscape pichu
  cluster: &cluster topaz

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

metrics-server:
  commonLabels:
    <<: *tags
  podAnnotations:
    <<: *tags
