serviceTree:
  landscape: &landscape suicune
  cluster: &cluster mica-talc

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

metrics-server:
  commonLabels:
    <<: *tags
  podAnnotations:
    <<: *tags
