serviceTree:
  landscape: &landscape raichu
  cluster: &cluster amber

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

metrics-server:
  commonLabels:
    <<: *tags
  podAnnotations:
    <<: *tags
